apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: microservice-ecosystem
deploy:
  kubectl:
    manifests:
    - calculator-service/target/classes/META-INF/dekorate/kubernetes.json
    - calculator-service/target/classes/META-INF/dekorate/kubernetes.yml

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: dave/calculator-service
      context: .
      jib: {}

  local:
    push: false     # Set true to a push built images to remote Docker repository